import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Faceless Video System: AI YouTube Automation | CreatorOps',
  description: 'The ultimate system for faceless YouTube growth. Script, voiceover, and thumbnail concepts generated by AI.',
  keywords: ['faceless YouTube channel', 'YouTube automation AI', 'video script generator'],
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return <>{children}</>;
}
